### ISSUE TITLE
Fitting a large model on a GPU

### ISSUE THREAD

**Issue by Guillermo-Hidalgo-Gadea** [cvxgrp/pymde#12]
Hi Akshay, 

I was trying to fit my data to a pymde.datasets object and plot the embedding with the following code:
```
# convert 30 features to torch.tensor
print('data shape: ' + str(latent_vector.iloc[:,:-1].shape))
data = torch.tensor(latent_vector.iloc[:,:-1].values)
print(type(data))

# convert target to attributes dictionary
print('target shape: ' + str(latent_vector.iloc[:,-1:].shape))
attributes = {'predictions': latent_vector.iloc[:,-1:].values}
print(type(attributes))

# create pyMDE object from data and attributes
dataset = pymde.datasets.Dataset(data, attributes)
print(type(dataset))
print(type(dataset.data))
print(type(dataset.attributes))

# embedding
mde = pymde.preserve_neighbors(dataset.data, verbose=True)
embedding = mde.embed(verbose=True)

#  visualize the embedding
pymde.plot(embedding, color_by=dataset.attributes['predictions'])
```
print:
```
data shape: (1286810, 30)
<class 'torch.Tensor'>
target shape: (1286810, 1)
<class 'dict'>
<class 'pymde.datasets.Dataset'>
<class 'torch.Tensor'>
<class 'dict'>
Mar 25 12:17:28 PM: Computing 15-nearest neighbors, with max_distance=None
Thu Mar 25 12:17:28 2021 Building RP forest with 32 trees
Thu Mar 25 12:17:36 2021 NN descent for 20 iterations
	 1  /  20
	 2  /  20
	Stopping threshold met -- exiting after 2 iterations
Mar 25 12:18:04 PM: Computing quadratic initialization.
Mar 26 10:18:36 AM: Fitting a centered embedding into R^2, for a graph with 1286810 items and 23259581 edges.
Mar 26 10:18:36 AM: `embed` method parameters: eps=1.0e-05, max_iter=300, memory_size=10
Mar 26 10:18:42 AM: iteration 000 | distortion 2.465605 | residual norm 0.889904 | step length 0.00157404 | percent change 8.72897e-05
Mar 26 10:20:09 AM: iteration 030 | distortion 0.208646 | residual norm 0.000285891 | step length 1 | percent change 5.24053
Mar 26 10:21:41 AM: iteration 060 | distortion 0.099533 | residual norm 0.000107316 | step length 1 | percent change 1.34718
Mar 26 10:23:11 AM: iteration 090 | distortion 0.076901 | residual norm 8.17378e-05 | step length 1 | percent change 0.672268
Mar 26 10:24:42 AM: iteration 120 | distortion 0.066920 | residual norm 6.65433e-05 | step length 1 | percent change 0.450777
Mar 26 10:26:10 AM: iteration 150 | distortion 0.060995 | residual norm 5.49753e-05 | step length 1 | percent change 0.325744
Mar 26 10:27:37 AM: iteration 180 | distortion 0.057445 | residual norm 4.82097e-05 | step length 1 | percent change 0.255452
Mar 26 10:29:05 AM: iteration 210 | distortion 0.054821 | residual norm 4.50138e-05 | step length 1 | percent change 0.183081
Mar 26 10:30:33 AM: iteration 240 | distortion 0.052996 | residual norm 3.57502e-05 | step length 1 | percent change 0.162585
Mar 26 10:32:01 AM: iteration 270 | distortion 0.051759 | residual norm 3.04045e-05 | step length 1 | percent change 0.115733
Mar 26 10:33:27 AM: iteration 299 | distortion 0.050823 | residual norm 2.29072e-05 | step length 1 | percent change 0.139809
Mar 26 10:33:27 AM: Finished fitting in 890.999 seconds and 300 iterations.
Mar 26 10:33:27 AM: average distortion 0.0508 | residual norm 2.3e-05
```

I encountered the following problem:
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-118-a135ee68ae95> in <module>
     20 
     21 #  visualize the embedding
---> 22 pymde.plot(embedding, color_by=dataset.attributes['predictions'])

~\Anaconda3\envs\vame\lib\site-packages\pymde\experiment_utils.py in plot(X, color_by, color_map, colors, edges, axis_limits, background_color, marker_size, figsize_inches, savepath)
    504         background_color=background_color,
    505         s=marker_size,
--> 506         figsize=figsize_inches,
    507     )
    508 

~\Anaconda3\envs\vame\lib\site-packages\pymde\experiment_utils.py in _plot(X, color_by, edges, s, figsize, colors, cmap, lim, background_color, title, tight, savepath)
    357                 edgecolor=[],
    358                 cmap=cmap,
--> 359                 alpha=1.0,
    360             )
    361         elif colors is not None:

~\Anaconda3\envs\vame\lib\site-packages\matplotlib\__init__.py in inner(ax, data, *args, **kwargs)
   1445     def inner(ax, *args, data=None, **kwargs):
   1446         if data is None:
-> 1447             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1448 
   1449         bound = new_sig.bind(ax, *args, **kwargs)

~\Anaconda3\envs\vame\lib\site-packages\matplotlib\cbook\deprecation.py in wrapper(*inner_args, **inner_kwargs)
    409                          else deprecation_addendum,
    410                 **kwargs)
--> 411         return func(*inner_args, **inner_kwargs)
    412 
    413     return wrapper

~\Anaconda3\envs\vame\lib\site-packages\matplotlib\axes\_axes.py in scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, plotnonfinite, **kwargs)
   4451             self._parse_scatter_color_args(
   4452                 c, edgecolors, kwargs, x.size,
-> 4453                 get_next_color_func=self._get_patches_for_fill.get_next_color)
   4454 
   4455         if plotnonfinite and colors is None:

~\Anaconda3\envs\vame\lib\site-packages\matplotlib\axes\_axes.py in _parse_scatter_color_args(c, edgecolors, kwargs, xsize, get_next_color_func)
   4250             isinstance(c, str)
   4251             or (np.iterable(c) and len(c) > 0
-> 4252                 and isinstance(cbook.safe_first_element(c), str)))
   4253 
   4254         def invalid_shape_exception(csize, xsize):

~\Anaconda3\envs\vame\lib\site-packages\matplotlib\cbook\__init__.py in safe_first_element(obj)
   1669         raise RuntimeError("matplotlib does not support generators "
   1670                            "as input")
-> 1671     return next(iter(obj))
   1672 
   1673 

NotImplementedError: multi-dimensional sub-views are not implemented
````
It seems like the` color_by=dataset.attributes['predictions']` is the problem, as I can plot the embedding without coloring, althouth there is not much to see:

![Download](https://user-images.githubusercontent.com/66069491/112619613-d4ccea80-8e27-11eb-8136-104eadbb09d4.png)

This is how the umap embedding looked like from `import umap`:
![Download (1)](https://user-images.githubusercontent.com/66069491/112619890-24abb180-8e28-11eb-9387-1ca7c8417ff6.png)

Do you have a hunch of what I am missing?

Last side note: `mde.device` shows that my GPU is not detected (or at least not engaged) `device(type='cpu')` and the embedding took 22 hours, any idea on that?

Thanks in advance!

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Hi Akshay. 

sorry for posting to quick!
My attributes were a individually nested list and had to be flattened first. This did the trick.

Any idea though how to:
1) Use GPU for faster embedding
2) Zoom in to the center cluster of the figure above (and loose the outliers)?

**Comment by akshayka** [comment]
Hi! Thanks for reporting this issue, and for being a very early user of PyMDE.

1. To use a GPU, pass in `device='cuda'` to `preserve_neighbors`: `pymde.preserve_neighbors(dataset.data, device='cuda', verbose=True)`. To see if PyTorch can detect your GPU, print the return value of `torch.cuda.is_available()`
2. The `plot` method returns the Matplotlib `Axis` object on which the embedding was plotted. On that object you can call, eg, `set_xlim(-20, 20)`, `set_ylim(-20, 20)`.

I suspect that the embedding needed to be optimized for a bit more time. To do that you could decrease `eps` (to, say, ``1e-6` or `1e-8` if you want to be very careful), and increase `max_iter` (to, say, 600 or 1000, to be safe). (These are keyword arguments to the `embed` method.)

But 22 hours is a very long time! I suspect you don't want to run for that long, or any longer.

Is there any chance you could share your data with me? If so I can also take a crack at it.

**Comment by akshayka** [comment]
One more tip, regarding devices.

If you already have an `MDE` object on hand, you can transfer it to your GPU using `mde.to('cuda')`. To move it back to CPU, use `mde.to('cpu')`.

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Thank you for the quick reply!

I'm running the embedding again with your recommendations `mde.embed(eps = 1e-8, max_iter = 1000, verbose=True)` .
Now I actually hear the GPU running :)

I'll keep you posted, thank you!
